project:
  type: website
  output-dir: docs

website:
  title: "Model selection"
  reader-mode: false
  sidebar:
    style: "docked"
    search: true
    tools:
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/p-lemercier/Model-selection
          - text: Report a Bug
            url: https://github.com/p-lemercier/Model-selection/issues
    contents:
      - href: index.qmd
        text: Introduction
      - section: "Explanatory Variables"
        contents:
          - explanatory_variables/introduction.qmd
          - section: "Application of Restricted Cubic Splines"
            contents:
              - href: explanatory_variables/spline_linear.qmd
                text: Linear Regression
              - href: explanatory_variables/spline_logistic.qmd
                text: Logistic Regression
              - href: explanatory_variables/spline_cox.qmd
                text: Cox Proportional Hazards Regression
      - about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    code-fold: true
    toc: true

editor: visual

